arms/css/analysis/analysis.css
arms/html/analysisResource/content-container.html
arms/js/analysis/resource/chart/horizontalBarChart.js
arms/js/analysisResource.js
arms/js/common.js

1. 요구사항, 이슈 해결책 스택바 차트 제거
2. 1에서 생긴 공간으로 도넛 차트 이동
3. 2에서 생긴 공간에 태그 클라우드 추가
4. 그 외 해상도에 따른 차트 resize, No Data 일부 처리
트리맵 차트는 apache echarts로 교체 예정
See http://www.313.co.kr/jira/browse/ARMS-232 more details.
성능 측정 : [ZipKin] …

feat: [ARMS-232] #comment 레이아웃 변경 - 23.12.04

---

arms/html/analysisTime/content-container.html

:alien: refactor: [Frontend] #comment 일정 분석차트 y 스크롤 추가  - 23.12.05

---

arms/html/analysisTime/content-container.html

[ Backend-Core::Java-Service-Tree-Framework(JSTF)::chanho470 ] [Requirement Manage] http://www.a-rms.net
[NoSql Index] …

:alien: refactor : [Frontend] #comment 일정분석 차트 위치 수정  - 23.12.05

---

arms/js/analysisResource.js
arms/js/dashboard.js

See http://www.313.co.kr/jira/browse/ARMS-243 more details. …

feat: [ARMS-243] #comment 트리맵 차트 Full Size - 23.12.12

---

arms/js/analysisResource.js
arms/js/dashboard.js

#close #time 3h +review SR @dumbbelloper
See http://www.313.co.kr/jira/browse/ARMS-248 more details. …

feat: [ARMS-248] #comment 트리맵 차트 drill-down 가능하도록 개선 - 23.12.13

---

arms/html/analysisResource/content-container.html

태그 클라우드 설명 변경
See http://www.313.co.kr/jira/browse/ARMS-249 more details.
클러스터2 : …

feat: [ARMS-249] #comment 태그 클라우드 설명 추가 - 23.12.13

---

arms/html/dashboard/content-container.html
arms/js/dashboard.js

Sankey UI 개선(height 조정)
See http://www.313.co.kr/jira/browse/ARMS-250 more details.
클러스터1 : [Kubernetes] …

feat: [ARMS-250] #comment Sankey UI 개선 - 23.12.14

---

arms/js/analysisResource.js
arms/js/dashboard.js

See http://www.313.co.kr/jira/browse/ARMS-248 more details. …

feat: [ARMS-248] #comment 트리맵 차트 leafDepth 변경 - 23.12.15

---

Gruntfile.js
arms/js/analysis/resource/sankey.js
arms/js/analysisResource.js
arms/js/analysisScope.js
arms/js/dashboard.js

See http://www.313.co.kr/jira/browse/ARMS-253 more details. …

feat: [ARMS-253] #comment 코드 정리 - 23.12.16

---

arms/html/analysisTime/content-container.html
reference/jquery-plugins/info-chart-v1/js/D_analysisTime.js

:alien: refactor: [Frontend] #comment 버전별 타임라인 차트 오늘 날짜 표시 - 23.12.16

---

arms/js/dashboard.js
arms/js/reqStatus.js

Backend API return type 변경에 따른 ajax 코드 변경
See http://www.313.co.kr/jira/browse/ARMS-255 more details.
클러스터1 : [Kubernetes] …

feat: [ARMS-255] #comment 코드 정리 - 23.12.16

---

arms/html/analysisTime/content-container.html
arms/js/analysisTime.js
reference/jquery-plugins/info-chart-v1/js/timeline_analysisTime.js
reference/jquery-plugins/timelines-chart-2.11.8/src/show-time-marker.js

:alien: refactor: [Frontend] #comment 상세 타임라인 차트 호출 API 변경 적용 - 23.12.17

---

arms/js/analysisTime.js

- 임시 데이터 변경적용
[ Frontend-Web::Java-Service-Tree-Framework(JSTF)::chanho470 ]
[Requirement Manage] http://www.a-rms.net/
[Kubernetes] http://www.313.co.kr:31380/
[NoSql Index] …

👽 refactor: [Frontend] #comment 상세 타임라인 차트 호출 API 변경 적용 - 23.12.17

---

arms/html/analysisTime/content-container.html
arms/js/analysisTime.js

- 일자 범위 검색 기능 적용 #close #time 1h +review SR @313devops
[NoSql Index] …

:alien: refactor: [Frontend] #comment 상세 타임라인 차트 호출 API 변경 적용 - 23.12.19

---

arms/js/analysisScope.js

#close #time 3d +review SR @dumbbelloper
See http://www.313.co.kr/jira/browse/ARMS-256 more details. …

feat: [ARMS-256] #comment 트리바 Top 10 차트 - 23.12.21

---

arms/js/analysisScope.js

#close #time 10m +review SR @dumbbelloper
See http://www.313.co.kr/jira/browse/ARMS-263 more details. …

feat: [ARMS-263] #comment 트리바 차트 UI 개선 - 23.12.22

---

arms/html/analysisResource/content-container.html
arms/html/dashboard/content-container.html
arms/js/analysis/resource/treemap.js
arms/js/analysisResource.js
arms/js/dashboard.js

#close #time 3h +review SR @dumbbelloper
See http://www.313.co.kr/jira/browse/ARMS-266 more details. …

feat: [ARMS-266] #comment  트리맵 차트 Echarts -> Jit 변경  - 23.12.23

---

arms/html/analysisTime/content-container.html
arms/js/analysisTime.js

- 요구사항 기준 연관된이슈 업데이트 기준 선 적용
- 요구사항 기준 업데이트 추이 미 적용 상태 (라디오 버튼)
[ Frontend-Web::Java-Service-Tree-Framework(JSTF)::chanho470 ]
[Requirement Manage] http://www.a-rms.net/
[Kubernetes] http://www.313.co.kr:31380/
[MEM Admin] …

👽 feat: [Frontend] #comment 요구사항 기준 업데이트 추이 차트(등고선차트) 추가 - 23.12.27

---

arms/html/analysisTime/content-container.html
arms/js/analysisTime.js

- 데이터 없을 경우 처리
[ Frontend-Web::Java-Service-Tree-Framework(JSTF)::chanho470 ]
[Requirement Manage] http://www.a-rms.net/
[Kubernetes] http://www.313.co.kr:31380/
[NoSql Index] …

👽 refactor: [Frontend] #comment 등고선 차트 각 항목 y축 요구사항 제목으로 대체 처리 - 23.12.30

---

arms/js/dashboard.js

See http://www.313.co.kr/jira/browse/ARMS-273 more details. …

feat: [ARMS-273] #comment c3.js combination 버그 수정 - 23.12.30

---

arms/js/dashboard.js

See http://www.313.co.kr/jira/browse/ARMS-273 more details. …

feat: [ARMS-273] #comment c3.js combination 툴팁 기능 제거 - 23.12.30

---

arms/js/analysisScope.js

See http://www.313.co.kr/jira/browse/ARMS-263 more details. …

feat: [ARMS-263] #comment 트리바 반응형 - 23.12.31

---

arms/js/analysisScope.js

See http://www.313.co.kr/jira/browse/ARMS-275 more details. …

feat: [ARMS-275] #comment analysis scope 코드 정리 - 23.12.31

---

arms/html/analysisCost/content-container.html
arms/js/analysisCost.js

#2 요구 사항 별 단가 계산
=> 실질적 단가 파악하기 위함 BUT 직접 입력 또한 가능해야함(실질 평가 기준은 다를 수 있기 때문)
요구 사항 중요도 난이도 별 단가 계산
파이 차트는 난이도, 중요도 기준으로 비율 구분 
#4 인력 현황 그래프
=> 투입 인원의 기대값을 평가 가능
해당 인원의 처리 요구 사항 개수 기준으로 비용 산정 
해당 인원의 연봉 정보도 같이 보여줌
기본 아이디어: 연봉/12 = 1M/m
예시: 연봉 1200만원의 인원은 1달에 120만원 어치의 요구사항을 수행해야함 못하면 일 안한거 확인가능
[ Backend-Core::Java-Service-Tree-Framework(JSTF)::Advanc2d ]
[Requirement Manage] http://www.a-rms.net
[Docker Hub] …

:see_no_evil: feat : [Frontend] #comment 요구사항 단가 계산, 인력별 현황 그래프 샘플 - 24.01.17

---

arms/html/analysisCost/content-container.html
arms/js/analysisCost.js

- Cost 모든 이슈 별 단가 포션(버블) 셈플 차트
- Cost 버전 단가 투입 비용 비교 셈플 차트
- Cost 이슈별 단가 확인 셈플 차트 #close #time 1h +review SR @313devops
[ Backend-Core::Java-Service-Tree-Framework(JSTF)::chanho470 ] [Requirement Manage] http://www.a-rms.net …

:ailen: feat : [Frontend] #comment Cost 셈플 차트 삽입 - 24.01.21

---

arms/html/analysisCost/content-container.html
arms/js/analysis/resource/chart/simplePie.js
arms/js/analysisCost.js

1. 리소스 파이 차트 호버 시 짤리는 현상 제거
2. 요구사항 비용 분석 줌 기능 추가
3. 라벨 데이터 옵션 지정
[ Frontend::Java-Service-Tree-Framework(JSTF)::Advanc2d ] [Requirement Manage] http://www.a-rms.net
[DockerSwarm] …

:see_no_evil: refactor : [Frontend] #comment arms cost, resouce 변경사항 적용 - 24.01.28

---

arms/html/jiraServer/content-container.html
arms/js/jiraServer.js

:alien: feat: [Redmine] #comment Redmine 서버 등록 안내문구 추가- 24.03.28

---

arms/js/jiraServer.js

:alien: feat: [Redmine] #comment Redmine 갱신버튼 클릭시 테이블 리로드 - 24.03.28

---

arms/js/analysisCost.js

See https://dumbbelloper.atlassian.net/browse/DEMO-135 more details.
클러스터2 : …

⚡️feat: [DEMO-137] #comment 연봉 수정 API 인자 변경 - 24.03.31

---

arms/html/jiraServer/content-container.html

[ Frontend-Web::Java-Service-Tree-Framework(JSTF)::chanho470 ]
[Requirement Manage] http://www.a-rms.net
[DB Admin] …

:alien: feat: [RedMine #17] #comment 서버 등록 페이지 팝업 문구 중복 제거 - 24.03.31

---

arms/js/analysisCost.js

클러스터2 : [DockerSwarm] http://www.313.co.kr/portainer/#!/auth
디비 관리 : [DB Admin] …

⚡️feat: [DEMO-141] #comment 제품 비용 line 차트 구간 별 연봉 변경 내역 반영 - 24.04.02

---

arms/js/jiraServer.js

1. ServerType 적용 jiraProject -> almProject로 변경
2. jira_renew_issueType_issueStatus_under_cloud 메소드 -> jira_renew 메소드로 통합
갱신 작업 하나의 endpoint에서 처리 /jiraServer/{renewType}/renewNode.do
[DockerSwarm] …

🙈 refactor : [Frontend] #comment ALM서버와 ARMS DB 동기화 처리를 위한 리팩토링 - 24.04.02

---

arms/html/jiraServer/content-container.html
arms/js/jiraServer.js

:alien: feat: [RedMine#20] #comment 서버 등록 시 계정 검증 버튼 추가 - 24.04.02

---

arms/js/jiraServer.js

:see_no_evil: refactor : [PHM-134] #comment jiraServer.js intellij 간격 수정 - 24.04.03

---

arms/js/mapping.js

1. mapping 없을 경우 방어코드 처리
2. 메소드 리팩토링
[DockerSwarm] …

:see_no_evil: feat : [redmine-phm-84] #commentt 매핑관리 gojs link 처리 - 24.07.17

---

arms/html/mapping/content-container.html
arms/js/mapping.js
arms/js/mapping/gojs_setup.js

1. 노드 및 연결 데이터 저장 시 디코딩 문제 해결 -> 데이터 기반 DB 저장 기능 필요
2. 카테고리 하위의 암스 상태 노드 추가 시 카테고리 데이터 추가
3. 연결 key 데이터 변경(c_id 기반)
4. 코드 리팩토링
[Docker Hub] …

:see_no_evil: feat : [redmine-phm-84] #commentt 매핑관리 gojs link 처리 - 24.07.18

---

arms/js/mapping.js
arms/js/mapping/gojs_setup.js

1. ARMS 상태 편집 알림 추가
2. 연결 등록, 수정, 삭제 API 연동
3. 노드 삭제 API 추가
4. 노드 이동 막기 …

:see_no_evil: feat : [redmine-phm-84] #commentt 매핑관리 API 연동 2차 - 24.07.25

---

arms/js/mapping.js

…
1. 클라우드 지라 프로젝트별 이슈유형 - 이슈상태 API 호출
[DockerSwarm] …

:see_no_evil: feat : [redmine-phm-84] #commentt 매핑관리 API 연동 3차 - 24.07.28

---

arms/html/template/page-sidebar.html
arms/js/mapping.js

:see_no_evil: refactor : [redmine-phm-84] #comment 상태 관리 페이지 이동 - 24.08.14

---

arms/css/override.css
arms/html/template/page-sidebar.html
arms/js/reqAddTable.js

…
요구 관리 - 테이블 보기
1. Version 반영
2. Assignee 반영
3. select 박스 css 반영
[DockerSwarm] …

:see_no_evil: feat : [redmine-phm-84] #comment 요구 관리 - 테이블 보기 상태 동적 반영 - 24.08.15

---

arms/js/mapping.js
arms/js/reqAdd.js

1. reqAdd, mapping 페이지 플러그인 그룹 정리
2. Alert 창 문구 수정
[DockerSwarm] …

:see_no_evil: feat : [redmine-phm-84] #comment reqAdd, mapping 페이지 플러그인 그룹 정리 - 24.08.16

---

arms/js/analysisCost.js
arms/js/analysisResource.js
arms/js/analysisScope.js
arms/js/analysisTime.js
arms/js/jiraConnection.js

:see_no_evil: refactor : [redmine-phm-84] #comment 분석 페이지 플러그인 그룹 정리 - 24.08.18

---

arms/js/mapping.js

:see_no_evil: feat : [redmine-phm-84] #comment 상태관리 삭제로직 변경 작업 1차 상태 변경 API 미반영 - 24.08.22

---

arms/html/mapping/content-container.html
arms/js/mapping.js

1. 요구사항 상태 삭제 후 전체 요구사항 상태 업데이트 호출 추가
2. Endpoint 변경 및 파라미터 추가
3. 삭제 전 상태 disabled 처리 추가
[Kubernetes] …

:see_no_evil: feat : [redmine-phm-84] #comment 상태 삭제 후 상태 업데이트 처리 추가 - 24.08.24

---

arms/js/mapping.js
arms/js/mapping/gojs_setup.js

…
1. 상태 카테고리 조회 API 순서 변경
2. 코드 리팩토링
3. go js 노드 수정 삭제 우측 마우스 버튼 활성화
4. 상태 더블 클릭 수정 제거
5. X버튼 제거
[Kubernetes] …

:see_no_evil: feat : [redmine-phm-84] #comment 상태 관리 go js 수정 삭제 우측 마우스 버튼 활성화 - 24.08.25

---

arms/html/mapping/content-container.html
arms/js/mapping.js

1. default 설정 관련 코드 추가(현재 미사용)
2. 사용되지 않는 코드 정리
[DockerSwarm] …

:see_no_evil: feat : [redmine-phm-84] #comment 상태 기본 설정 관련 코드 추가  - 24.08.26

---

arms/js/jiraServer.js
arms/js/reqGantt.js

1. reqGantt.js 플러그인 그룹 4개로 정리
2. 사용되지 않는 코드 정리
[DockerSwarm] …

:see_no_evil: refactor : [redmine-phm-84] #comment jiraServer.js, reqGantt.js 사용되지 않는 코드 정리 - 24.08.31

---

arms/js/mapping.js

1. 상태 관리 페이지 접속 시 상태 카테고리, 상태만 기본 화면에 뜨도록 처리
[DockerSwarm] …

:see_no_evil: feat : [redmine-phm-84] #comment 상태 관리 - 상태 카테고리, 상태 호출 - 24.09.01
